---
# yamllint disable rule:line-length
argument_specs:
  main:
    short_description: "Prometheus MySQLd Exporter"
    description:
      - "Deploy prometheus L(mysqld_exporter,https://github.com/prometheus/mysqld_exporter) using ansible"
    author:
      - "Kien Nguyen Tuan"
    options:
      mysqld_exporter_version:
        description: "MySQLd exporter package version. Also accepts latest as parameter."
        default: "0.15.1"
      mysqld_exporter_web_listen_address:
        description: "Address on which mysqld_exporter will listen"
        default: "{{ api_interface_address }}:9104"
      mysqld_exporter_web_telemetry_path:
        description: "Path under which to expose metrics"
        default: "/metrics"
      mysqld_exporter_config_dir:
        description: "The path where exporter configuration is stored"
        default: "/etc/ansitheus/mysqld_exporter"
      mysqld_exporter_target_host:
        description: "The target MySQL host"
        default: "{{ api_interface_address }}"
      mysqld_exporter_target_port:
        description: "The target MySQL port"
        default: 3306
      mysqld_exporter_target_socket:
        description: "The target MySQL unix socket"
      mysqld_exporter_username:
        description: "The username for MySQL login"
        default: "exporter"
      mysqld_exporter_password:
        description: "The password for MySQL login"
        default: "secret"
      mysqld_exporter_enabled_collectors:
        description:
          - "List of dicts defining additionally enabled collectors and their configuration."
          - "It adds collectors to L(those enabled by default,https://github.com/prometheus/mysqld_exporter#enabled-by-default)."
        type: "list"
        default: []
      mysqld_exporter_disabled_collectors:
        description:
          - "List of disabled collectors."
          - "By default mysqld_exporter disables collectors listed L(here,https://github.com/prometheus/mysqld_exporter#disabled-by-default)."
        type: "list"
        elements: "str"
      mysqld_exporter_tls_server_config:
        description:
          - "Configuration for TLS authentication."
          - "Keys and values are the same as in L(mysqld_exporter docs,https://github.com/prometheus/mysqld_exporter/blob/master/https/README.md#sample-config)."
        type: "dict"
      mysqld_exporter_http_server_config:
        description:
          - "Config for HTTP/2 support."
          - "Keys and values are the same as in L(mysqld_exporter docs,https://github.com/prometheus/mysqld_exporter/blob/master/https/README.md#sample-config)."
        type: "dict"
      mysqld_exporter_basic_auth_users:
        description: "Dictionary of users and password for basic authentication. Passwords are automatically hashed with bcrypt."
        type: "dict"
      mysqld_exporter_config_flags_extra:
        description:
          - "Additional configuration flags passed to mysqld-exporter binary at startup"
        type: "dict"
