---
- name: Validate alertmanager config
  vars:
    service_name: "alertmanager"
    service: "{{ alertmanager_services[service_name] }}"
  ansible.builtin.command: >
    /usr/bin/docker run --rm -v {{ alertmanager_config_dir }}:/etc/alertmanager {{ amtool_image }} sh -c 'amtool \
            check-config /etc/alertmanager/config.yml'
  when:
    - inventory_hostname in groups[service.group]
    - service.enabled | bool
    - alertmanager_config.changed | bool

- name: Reload alertmanager config
  vars:
    service_name: "alertmanager"
    service: "{{ alertmanager_services[service_name] }}"
  ansible.builtin.uri:
    url: http://{{ alertmanager_vip_address if alertmanager_vip_address is defined and alertmanager_vip_address != "" else api_interface_address }}:{{ alertmanager_port }}/-/reload
    method: POST
    use_proxy: false
  register: result
  retries: 5
  delay: 20
  until: result.status == 200
  when:
    - inventory_hostname in groups[service.group]
    - service.enabled | bool
    - alertmanager_config.changed | bool
      or alertmanager_custom_templates.changed | bool
