---
- name: Validate alertmanager config
  vars:
    service_name: "alertmanager"
    service: "{{ alertmanager_services[service_name] }}"
  ansible.builtin.command: >
    /usr/bin/docker run --rm -v {{ alertmanager_config_dir }}:/etc/alertmanager {{ amtool_image }} sh -c 'amtool \
            check-config /etc/alertmanager/config.yml'
  when:
    - inventory_hostname in groups[service.group]
    - service.enabled | bool
    - alertmanager_config.changed | bool

# NOTE(kiennt26): Reloading the config by sending SIGHUP to the main process, instead of sending a POST request
#                 to the /-/reload endpoint, because the latter doesn't work when the basic auth is enabled.
#                 The password for the basic auth is encrypted using bcrypt, and I don't want to store the raw password
#                 The SIGHUP signal is sent to the process with PID 1 in the container, which is the main process.
- name: Reload alertmanager config
  vars:
    service_name: "alertmanager"
    service: "{{ alertmanager_services[service_name] }}"
  ansible.builtin.command: >
    /usr/bin/docker exec -i {{ alertmanager_container_name }} kill -SIGHUP 1
  register: result
  retries: 5
  delay: 20
  until: result.rc == 0
  when:
    - inventory_hostname in groups[service.group]
    - service.enabled | bool
    - alertmanager_config.changed | bool
      or alertmanager_custom_templates.changed | bool
