---
- name: Reload alertmanager config
  vars:
    service_name: "alertmanager"
    service: "{{ alertmanager_services[service_name] }}"
  uri:
    url: http://{{ api_interface_address }}:{{ alertmanager_port }}/-/reload
    method: POST
  register: result
  retries: 5
  delay: 20
  until: result.status == 200
  when:
    - inventory_hostname in groups[service.group]
    - service.enabled | bool
    - alertmanager_config.changed | bool
      or alertmanager_custom_confs.changed | bool
      or alertmanager_custom_templates.changed | bool
