---
- name: Install Docker
  ansible.builtin.include_role:
    name: geerlingguy.docker
    apply:
      become: true

- name: Install Docker pip package
  ansible.builtin.include_role:
    name: geerlingguy.pip
    apply:
      become: true
  vars:
    pip_install_packages:
      - name: docker

- name: Create directory
  become: true
  file:
    path: "{{ ansitheus_custom_config_dir }}"
    state: directory
    recurse: yes
    mode: 0755

- name: Login private registry
  become: true
  community.docker.docker_login:
    registry: "{{ docker_registry }}"
    username: "{{ docker_registry_username }}"
    password: "{{ docker_registry_password }}"
  when: docker_registry is defined and docker_registry is not none
