---
- name: Uninstall old versions
  package:
    name: "{{ item }}"
    state: absent
  with_items:
    - docker
    - docker-client
    - docker-client-latest
    - docker-latest
    - docker-latest-logrotate
    - docker-common
    - docker-engine

- name: Disable SELinux
  selinux:
    policy: targeted
    state: disabled

- name: Find custom yum repositoty files
  local_action:
    module: find
    path: "{{ ansitheus_custom_conf }}/yum-repository/"
    pattern: "*.repo"
  run_once: true
  register: find_yum_repository
  when:
    - use_local_repo | bool

- name: Copying over custom yum repositoty files
  copy:
    src: "{{ item.path }}"
    dest: "{{ yum_repository_dir }}/{{ item.path | basename }}"
    mode: "0660"
  when:
    - find_yum_repository is defined and find_yum_repository.files | length > 0
    - use_local_repo | bool
  with_items: "{{ find_yum_repository.files }}"
  become: true

- name: Add Docker's official GPG key
  rpm_key:
    key: https://download.docker.com/linux/centos/gpg
    state: present
  when: not use_local_repo | bool

- name: Add Docker repository
  get_url:
    url: "{{ docker_yum_repository }}"
    dest: "/etc/yum.repos.d/{{ docker_pkg }}.repo"
    owner: root
    group: root
    mode: 0644
  when: not use_local_repo | bool

- name: Configure Docker Edge repo
  ini_file:
    dest: "/etc/yum.repos.d/{{ docker_pkg }}.repo"
    section: "{{ docker_pkg }}-edge"
    option: enabled
    value: "{{ docker_yum_repo_enable_edge | bool }}"
  when: not use_local_repo | bool

- name: Configure Docker Test repo
  ini_file:
    dest: "/etc/yum.repos.d/{{ docker_pkg }}.repo"
    section: "{{ docker_pkg }}-test"
    option: enabled
    value: "{{ docker_yum_repo_enable_test | bool }}"
  when: not use_local_repo | bool
