---
- name: Validate prometheus config
  vars:
    service_name: "prometheus"
    service: "{{ prometheus_services[service_name] }}"
  ansible.builtin.command: >
    /usr/bin/docker run --rm -v {{ prometheus_config_dir }}:/etc/prometheus {{ promtool_image }} sh -c 'promtool \
            check config /etc/prometheus/prometheus.yml'
  when:
    - inventory_hostname in groups[service.group]
    - service.enabled | bool
    - prometheus_confs.changed | bool
      or prometheus_alert_confs.changed | bool
      or prometheus_file_sd_confs.changed | bool

# NOTE(kiennt26): Reloading the config by sending SIGHUP to the main process, instead of sending a POST request
#                 to the /-/reload endpoint, because the latter doesn't work when the basic auth is enabled.
#                 The password for the basic auth is encrypted using bcrypt, and I don't want to store the raw password
#                 The SIGHUP signal is sent to the process with PID 1 in the container, which is the main process.
- name: Reload prometheus config
  vars:
    service_name: "prometheus"
    service: "{{ prometheus_services[service_name] }}"
  ansible.builtin.command: >
    /usr/bin/docker exec -i {{ prometheus_container_name }} kill -SIGHUP 1
  register: result
  retries: 5
  delay: 20
  until: result.rc == 0
  when:
    - inventory_hostname in groups[service.group]
    - service.enabled | bool
    - prometheus_confs.changed | bool
      or prometheus_alert_confs.changed | bool
      or prometheus_file_sd_confs.changed | bool
      or prometheus_tls_confs.changed | bool

# NOTE(kiennt26): Force restart keepalived to trigger notify script.
#                 Prometheus instances must be deployed in the same nodes as Haproxy and Keepalived.
- name: Restart keepalived service
  ansible.builtin.service:
    name: "keepalived"
    state: "restarted"
  register: keepalived_restart
  when:
    - inventory_hostname in groups['haproxy'] and inventory_hostname in groups['prometheus']
    - prometheus_active_passive_mode | bool
    - prometheus_container.changed | bool
