---
- name: Reload prometheus_alertmanager config
  vars:
    service_name: "prometheus_alertmanager"
    service: "{{ prometheus_alertmanager_services[service_name] }}"
    ansible_interface: "ansible_{{ ansitheus_network_interface }}"
    prometheus_alertmanager_ip_address: "{{ hostvars[inventory_hostname][ansible_interface]['ipv4']['address'] }}"
  uri:
    url: http://{{ prometheus_alertmanager_ip_address }}:{{ prometheus_alertmanager_port }}/-/reload
    method: POST
  register: result
  retries: 5
  delay: 20
  until: result.status == 200
  when:
    - inventory_hostname in groups[service.group]
    - service.enabled | bool
    - prometheus_alertmanager_confs.changed | bool
      or prometheus_alertmanager_custom_confs.changed | bool
