---
project_name: "fluentd"

fluentd_services:
  fluentd:
    container_name: "fluentd"
    group: "fluentd"
    enabled: "{{ enable_fluentd | bool }}"
    image: "{{ fluentd_image_full }}"
    privileged: "no"
    network_mode: "host"
    restart_policy: "unless-stopped"
    state: "started"
    volumes:
      - "{{ fluentd_conf }}:/fluentd/etc:rw"
      - "/etc/localtime:/etc/localtime:ro"

fluentd_conf: "{{ ansitheus_conf }}/fluentd/"

##########
# Docker #
##########

fluentd_image: "{{ docker_registry ~ '/' if docker_registry else '' }}{{ fluentd_docker_namespace }}/fluentd"
fluentd_tag: "{{ fluentd_ver }}"
fluentd_image_full: "{{ fluentd_image }}:{{ fluentd_tag }}"
fluentd_log_prefix: "am"
fluentd_flush_interval: "15s"
