---
# defaults file for common
yum_repository_conf: "{{ ansitheus_config_dir }}/yum-repository"
yum_repository_dir: "/etc/yum.repos.d"

pip_docker_ver: "4.0.2"

#############################################
# Original Docker source
# Yum - Only be used if use_local_repo is yes
#############################################

# Debian/Ubuntu
docker_apt_release_channel: stable
docker_apt_arch: amd64
docker_apt_repository: "deb [arch={{ docker_apt_arch }}] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} {{ docker_apt_release_channel }}"
docker_apt_ignore_key_error: "yes"
docker_apt_key: "9DC858229FC7DD38854AE2D88D81803C0EBFCD88"

# CentOS/RedHat/Fedora
docker_yum_repository: https://download.docker.com/linux/{{ (ansible_distribution == "Fedora") | ternary("fedora","centos") }}/docker-{{ docker_edition }}.repo
docker_yum_repo_enable_edge: "no"
docker_yum_repo_enable_test: "no"
