---
######################
# Service VIP address
######################
ansitheus_vip_address: ""
prometheus_vip_address: "{{ ansitheus_vip_address }}"
alertmanager_vip_address: "{{ ansitheus_vip_address }}"

ansitheus_network_interface: "eth0"
keepalived_virtual_router_id: "82"
ansitheus_config_dir: "/etc/ansitheus"
ansitheus_custom_config_dir: "{{ ansitheus_config_dir }}/config"
# The group which own node_config_directory, you can use a non-root
config_owner_user: "root"
config_owner_group: "root"

network_interface: "{{ network_interface }}"
api_interface: "{{ network_interface }}"
api_interface_address: "{{ hostvars[inventory_hostname]['ansible_' + api_interface]['ipv4']['address'] }}"

###############
# Haproxy Users
###############
prometheus_server_user: "admin"
prometheus_alertmanager_user: "admin"

###################
# Haproxy Passwords
###################

keepalived_password: "{{ keepalived_password }}"
# Passwords that are used for HAProxy basic auth
alertmanager_basic_auth_password: "{{ alertmanager_basic_auth_password }}"
prometheus_basic_auth_password: "{{ prometheus_basic_auth_password }}"

################
# Docker options
################

docker_registry: "{{ docker_registry if docker_registry else '' }}"
docker_namespace: "{{ docker_namespace if docker_namespace else '' }}"
docker_registry_username: "{{ docker_registry_username if docker_registry_username else ''}}"
docker_registry_password: "{{ docker_registry_password if docker_registry_password else '' }}"
docker_log_driver: "json-file"
docker_log_opts:
  max-size: 30m
  max-file: 3

##################
# Service options
##################

enable_prometheus: "yes"
enable_node_exporter: "yes"
enable_cadvisor: "yes"
enable_grafana: "no"
enable_alertmanager: "yes"
enable_haproxy_keepalived: "yes"

##################
# Port mappings
#################

prometheus_port: "9090"
alertmanager_port: "9093"
alertmanager_cluster_port: "9094"
node_exporter_port: "9100"
cadvisor_port: "8080"
grafana_port: "3000"

###############
# Image version
###############

prometheus_version: "2.52.0"
alertmanager_version: "0.27.0"
node_exporter_version: "1.8.0"
cadvisor_version: "v0.35.0"
grafana_version: "7.2.2"
haproxy_version: "2.3.1"
keepalived_version: "2.0.17"

##########################
# Service docker namespace
##########################

prometheus_docker_namespace: "{{ docker_namespace if docker_namespace else 'prom' }}"
alertmanager_docker_namespace: "{{ docker_namespace if docker_namespace else 'prom' }}"
node_exporter_docker_namespace: "{{ docker_namespace if docker_namespace else 'prom' }}"
grafana_docker_namespace: "{{ docker_namespace if docker_namespace else 'grafana' }}"
cadvisor_docker_namespace: "{{ docker_namespace if docker_namespace else 'cadvisor' }}"
keepalived_docker_namespace: "{{ docker_namespace if docker_namespace else 'kiennt26' }}"
haproxy_docker_namespace: "{{ docker_namespace if docker_namespace else '' }}"

####################
# Prometheus options
####################

prometheus_storage_retention: "90d"
prometheus_external_labels: # This is a dictionary variable
  monitor: "cloud"
prometheus_scrape_interval: "60s"
prometheus_scrape_timeout: "30s"
prometheus_evaluation_interval: "120s"

#################
# Grafana options
#################

##################
# Grafana options
##################
# Please check http://docs.grafana.org/installation/configuration/
grafana_database:
  type: sqlite3
  # name: grafana
  # host: 127.0.0.1
  # usere: admin
  # password: "KbJdz8*U" # Please change me
grafana_remote_cache: {}
grafana_security:
  admin_user: "admin"
  admin_password: "YJ97&Yz$" # Please change me
  #  secret_key: ""
  #  login_remember_days: 7
  #  cookie_username: grafana_user
  #  cookie_remember_name: grafana_remember
  #  disable_gravatar: true
  #  data_source_proxy_whitelist:
grafana_session: {}
#  provider: file
#  provider_config: "sessions"
# grafana authentication mechanisms
grafana_auth: {}
#  disable_login_form: false
#  oauth_auto_login: false
#  disable_signout_menu: false
#  signout_redirect_url: ""
#  anonymous:
#    org_name: "Main Organization"
#    org_role: Viewer
#  ldap:
#    config_file: "/etc/grafana/ldap.toml"
#    allow_sign_up: false
#  basic:
#    enabled: true
grafana_users:
  allow_sign_up: false
  # allow_org_create: true
  # auto_assign_org: true
  auto_assign_org_role: Viewer
  # login_hint: "email or username"
  default_theme: dark
  # external_manage_link_url: ""
  # external_manage_link_name: ""
  # external_manage_info: ""

###############
# Alert options
###############

alert_via_email: "yes"
alert_mail_account: "{{ alert_mail_acount }}"
alert_mail_host: "{{ alert_mail_host }}"
alert_mail_port: "{{ alert_mail_port }}"
alert_mail_password: "{{ alert_mail_password }}"
alert_via_slack: "no"
alert_slack_channel: "{{ alert_slack_channel }}"
alert_slack_webhook_id: "{{ alert_slack_webhook_id }}"
