---
- name: Ensuring config directory exist
  ansible.builtin.file:
    path: "{{ grafana_conf }}"
    state: "directory"
    owner: "{{ config_owner_user }}"
    group: "{{ config_owner_group }}"
    mode: "0755"

- name: Find grafana plugins files (.zip)
  local_action:
    module: find
    path: "{{ ansitheus_custom_config_dir }}/grafana/plugins/"
    pattern: "*.zip"
  run_once: True
  register: grafana_plugins_zip

- name: Ensuring custom plugin directory exist
  ansible.builtin.file:
    path: "{{ grafana_conf }}/plugins"
    state: "directory"
    owner: "{{ config_owner_user }}"
    group: "{{ config_owner_group }}"
    mode: "0755"
  when: grafana_plugins_zip is defined and grafana_plugins_zip.files | length > 0

- name: Extract plugins .zip to destination
  unarchive:
    src: "{{ ansitheus_custom_config_dir }}/grafana/plugins/{{ item.path | basename }}"
    dest: "{{ grafana_conf }}/plugins"
    mode: "0755"
  register: grafana_plugins
  when: grafana_plugins_zip is defined and grafana_plugins_zip.files | length > 0
  with_items: "{{ grafana_plugins_zip.files }}"
  notify:
    - Recreate grafana container

- name: Copying over grafana config file
  template:
    src: "{{ item }}"
    dest: "{{ ansitheus_config_dir }}/grafana/grafana.ini"
    mode: "0755"
  register: grafana_confs
  with_first_found:
    - "{{ ansitheus_custom_config_dir }}/grafana/{{ inventory_hostname }}/grafana.ini"
    - "{{ ansitheus_custom_config_dir }}/grafana/grafana.ini"
    - "{{ role_path }}/templates/grafana.ini.j2"
  notify:
    - Recreate grafana container

- name: Find extra configuration files
  local_action:
    module: find
    path: "{{ ansitheus_custom_config_dir }}/grafana/"
    pattern: "*.yaml"
  changed_when: False
  run_once: True
  register: grafana_extra_confs

- name: Copying over extra configuration files
  template:
    src: "{{ item.path }}"
    dest: "{{ ansitheus_config_dir }}/grafana/{{ item.path | basename }}"
    mode: "0755"
  register: grafana_extra_confs
  when: grafana_extra_confs is defined and grafana_extra_confs.files | length > 0
  with_items: "{{ grafana_extra_confs.files }}"
  notify:
    - Recreate grafana container

- name: Check grafana containers
  community.general.docker_container:
    name: "{{ item.value.container_name }}"
    image: "{{ item.value.image }}"
    volumes: "{{ item.value.volumes }}"
    state: "{{ item.value.state }}"
    restart_policy: "{{ item.value.restart_policy }}"
    network_mode: "{{ item.value.network_mode }}"
    log_driver: "{{ item.value.log_driver }}"
    log_options: "{{ item.value.log_options }}"
  with_dict: "{{ grafana_services }}"
