---
- name: Pull image without running grafana container
  docker_container:
    name: "{{ item.value.container_name }}"
    image: "{{ item.value.image }}"
    pull: "yes"
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ grafana_services }}"
