---
prometheus_exporter_services:
  node_exporter:
    container_name: "node_exporter"
    group: "prometheus_node_exporter"
    enabled: "{{ enable_node_exporter }}"
    image: "{{ prometheus_node_exporter_image }}"
    privileged: "no"
    state: "started"
    volumes:
      - "/proc:/host/proc:ro"
      - "/sys:/host/sys:ro"
      - "/:/rootfs:ro"
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--path.rootfs=/rootfs"
      - "--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
      - "--web.listen-address {{ api_interface_address }}:{{ node_exporter_port }}"
      - "--log.level={{ prometheus_node_exporter_log_level }}"
      - "--log.format={{ prometheus_node_exporter_log_format }}"
    restart_policy: "unless-stopped"
    network_mode: "host"
    port: "{{ node_exporter_port }}"
    log_driver: "{{ prometheus_node_exporter_log_driver }}"
    log_options: "{{ prometheus_node_exporter_log_opts }}"
  cadvisor:
    container_name: "cadvisor"
    group: "prometheus_cadvisor"
    enabled: "{{ enable_cadvisor }}"
    image: "{{ prometheus_cadvisor_image }}"
    privileged: "no"
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:rw"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
      - "/cgroup:/cgroup:ro"
    command:
      - "--listen_ip={{ api_interface_address }}"
      - "--port={{ cadvisor_port }}"
      - "--store_container_labels=false"
      - "--docker_only=true"
      - "--disable_root_cgroup_stats=true"
    restart_policy: "unless-stopped"
    state: "started"
    network_mode: "host"
    port: "{{ cadvisor_port }}"
    log_driver: "{{ prometheus_cadvisor_log_driver }}"
    log_options: "{{ prometheus_cadvisor_log_opts }}"

prometheus_node_exporter_image: "{{ docker_registry ~ '/' if docker_registry else '' }}{{ prometheus_docker_namespace }}/node-exporter:{{ node_exporter_version }}"
prometheus_cadvisor_image: "{{ docker_registry ~ '/' if docker_registry else 'gcr.io/' }}{{ cadvisor_docker_namespace }}/cadvisor:{{ cadvisor_version }}"

prometheus_node_exporter_log_driver: "{{ docker_log_driver }}"
prometheus_node_exporter_log_opts: "{{ docker_log_opts }}"
prometheus_cadvisor_log_driver: "{{ docker_log_driver }}"
prometheus_cadvisor_log_opts: "{{ docker_log_opts }}"

# Only log messages with the given severity or above. One of: [debug, info, warn, error]
prometheus_node_exporter_log_level: "info"
# Output format of log messages. One of: [logfmt, json]
prometheus_node_exporter_log_format: "json"
