---
# yamllint disable rule:line-length
argument_specs:
  main:
    short_description: "cAdvisor"
    description:
      - "Deploy L(cadvisor,https://github.com/google/cadvisor) using ansible"
    author:
      - "Kien Nguyen Tuan"
    options:
      cadvisor_version:
        description: "cAdvisor package version. Also accepts latest as parameter."
        default: "0.49.1"
      cadvisor_port:
        description: "Port on which cadvisor will listen"
        default: "8080"
      cadvisor_prometheus_endpoint:
        description: "Path under which to expose metrics"
        default: "/metrics"
      cadvisor_disable_metrics:
        description:
          - "comma-separated list of metrics to be disabled"
          - "(default advtcp,cpu_topology,cpuset,hugetlb,memory_numa,process,referenced_memory,resctrl,sched,tcp,udp)"
        type: "list"
        default: []
        choices: &metrics_choices
          - advtcp
          - app
          - cpu
          - cpuLoad
          - cpu_topology
          - cpuset
          - disk
          - diskIO
          - hugetlb
          - memory
          - memory_numa
          - network
          - oom_event
          - percpu
          - perf_event
          - process
          - referenced_memory
          - resctrl
          - sched
          - tcp
      cadvisor_enable_metrics:
        description: "comma-separated list of metrics to be enabled. If set, overrides 'cadvisor_disable_metrics'"
        default: []
        type: "list"
        choices: *metrics_choices
      cadvisor_docker_only:
        description: "do not report raw cgroup metrics, except the root cgroup"
        type: "bool"
        default: false
      cadvisor_housekeeping_interval:
        description: "interval between container housekeepings"
        type: "str"
        default: "30s"
      cadvisor_config_flags_extra:
        description:
          - "Additional configuration flags passed to cadvisor binary at startup"
        type: "dict"
