---
- name: Ensuring prometheus config directory exist
  file:
    path: "{{ prometheus_server_conf }}"
    state: "directory"
    owner: "{{ config_owner_user }}"
    group: "{{ config_owner_group }}"
    mode: "0755"
  become: true

- name: Find custom prometheus alert rule files
  local_action:
    module: find
    path: "{{ ansitheus_custom_conf }}/prometheus_server/rules/"
    pattern: "*.yml,*.yaml"
  run_once: true
  become: true
  register: prometheus_alert_rules

- name: Ensuring rules directory exist
  file:
    path: "{{ ansitheus_custom_conf }}/prometheus_server/rules/"
    state: "directory"
    mode: "0755"
  become: true
  when:
    - prometheus_alert_rules is defined and prometheus_alert_rules.files | length > 0

- name: Copying over custom prometheus alert rules files
  copy:
    src: "{{ item.path }}"
    dest: "{{ ansitheus_conf }}/prometheus_server/rules/{{ item.path | basename }}"
    mode: "0755"
  register: prometheus_alert_confs
  become: true
  when:
    - prometheus_alert_rules is defined and prometheus_alert_rules.files | length > 0
  with_items: "{{ prometheus_alert_rules.files }}"
  notify:
    - Reload prometheus_server config

- name: Check custom file_sd files exists
  local_action:
    module: find
    path: "{{ ansitheus_custom_conf }}/prometheus_server/file_sd"
    pattern: "*.json"
  run_once: true
  become: true
  register: prometheus_file_sd

- name: Ensuring file_sd directory exist
  file:
    path: "{{ ansitheus_custom_conf }}/prometheus_server/file_sd/"
    state: "directory"
    mode: "0755"
  become: true
  when:
    - prometheus_file_sd is defined and prometheus_file_sd.files | length > 0

- name: Copying over custom file_sd
  copy:
    src: "{{ item.path }}"
    dest: "{{ ansitheus_conf }}/prometheus_server/file_sd/{{ item.path | basename }}"
    mode: "0755"
  become: true
  register: prometheus_file_sd_confs
  with_items: "{{ prometheus_file_sd.files }}"
  when:
    - prometheus_file_sd is defined and prometheus_file_sd.files | length > 0
  notify:
    - Reload prometheus_server config

- name: Copying over prometheus config file
  template:
    src: "{{ item }}"
    dest: "{{ ansitheus_conf }}/prometheus_server/prometheus.yml"
    mode: "0755"
  register: prometheus_confs
  become: true
  with_first_found:
    - "{{ ansitheus_custom_conf }}/prometheus_server/{{ inventory_hostname }}/prometheus.yml"
    - "{{ ansitheus_custom_conf }}/prometheus_server/prometheus.yml"
    - "{{ role_path }}/templates/prometheus.yml.j2"
  notify:
    - Reload prometheus_server config

- name: Check prometheus_server containers
  become: true
  docker_container:
    name: "{{ item.value.container_name }}"
    image: "{{ item.value.image }}"
    volumes: "{{ item.value.volumes }}"
    command: "{{ item.value.command }}"
    state: "{{ item.value.state }}"
    restart_policy: "{{ item.value.restart_policy }}"
    privileged: "{{ item.value.privileged }}"
    network_mode: "{{ item.value.network_mode }}"
    log_driver: "{{ item.value.log_driver }}"
    log_options: "{{ item.value.log_options }}"
  with_dict: "{{ prometheus_server_services }}"
