---
- name: Stop and remove containers
  docker_container:
    name: "{{ item.value.container_name }}"
    state: "absent"
    keep_volumes: "{{ not destroy_include_volumes | bool }}"
  become: true
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ prometheus_server_services }}"

- name: Remove service configuration
  file:
    state: "absent"
    path: "{{ prometheus_server_conf }}"
  become: true
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ prometheus_server_services }}"

- name: Remove images
  docker_image:
    name: "{{ item.value.image }}"
    state: "absent"
  become: true
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
    - destroy_include_images | bool
  with_dict: "{{ prometheus_server_services }}"

- name: Remove volumes
  docker_volume:
    name: "{{ prometheus_server_volume }}"
    state: "absent"
  become: true
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
    - destroy_include_volumes | bool
  with_dict: "{{ prometheus_server_services }}"
