---
- name: Pull image without running Prometheus server container
  docker_container:
    name: "{{ item.value.container_name }}"
    image: "{{ item.value.image }}"
    pull: "yes"
  become: true
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ prometheus_server_services }}"
