---
- name: Restart mysqld_exporter container
  vars:
    service_name: "mysqld_exporter"
    service: "{{ mysqld_exporter_services[service_name] }}"
  become: true
  community.general.docker_container:
    name: "{{ service.container_name }}"
    image: "{{ service.image }}"
    volumes: "{{ service.volumes }}"
    command: "{{ service.command }}"
    state: "{{ service.state }}"
    restart: "yes"
    restart_policy: "{{ service.restart_policy }}"
    privileged: "{{ service.privileged }}"
    network_mode: "{{ service.network_mode }}"
    log_driver: "{{ service.log_driver }}"
    log_options: "{{ service.log_options }}"
  when:
    - inventory_hostname in groups[service.group]
    - service.enabled | bool
    - mysqld_exporter_web_conf.changed | bool or
      mysqld_exporter_my_cnf.changed | bool
