---
- name: Reload prometheus_server config
  vars:
    service_name: "prometheus_server"
    service: "{{ prometheus_server_services[service_name] }}"
    ansible_interface: "ansible_{{ ansitheus_network_interface }}"
    prometheus_server_ip_address: "{{ hostvars[inventory_hostname][ansible_interface]['ipv4']['address'] }}"
  uri:
    url: http://{{ prometheus_server_ip_address }}:{{ prometheus_server_port }}/-/reload
    method: POST
  register: result
  retries: 5
  delay: 20
  until: result.status == 200
  when:
    - inventory_hostname in groups[service.group]
    - service.enabled | bool
    - prometheus_confs.changed | bool
      or prometheus_alert_confs.changed | bool
