---
# EXAMPLE CONFIGS - MORE IN ansible/group_vars/all.yml

######################
# Service VIP address
######################
ansitheus_vip_address: "10.10.10.1"

ansitheus_network_interface: "eth0"
keepalived_virtual_router_id: "82"

# The group which own node_config_directory, you can use a non-root
config_owner_user: "root"
config_owner_group: "root"

network_interface: "eth0"

###################
# Haproxy Passwords
###################
keepalived_password: "{{ keepalived_password }}"
alertmanager_basic_auth_password: "{{ alertmanager_basic_auth_password }}"
prometheus_basic_auth_password: "{{ prometheus_basic_auth_password }}"

################
# Docker options
################

docker_registry: ""
docker_namespace: ""
docker_registry_username: ""
docker_registry_password: ""

##################
# Service options
##################

enable_prometheus: "yes"
enable_node_exporter: "yes"
enable_cadvisor: "yes"
enable_grafana: "no"
enable_alertmanager: "yes"
enable_haproxy_keepalived: "yes"

##################
# Port mappings
#################

prometheus_port: "9090"
alertmanager_port: "9093"
alertmanager_cluster_port: "9094"
node_exporter_port: "9100"
cadvisor_port: "8080"
grafana_port: "3000"

###############
# Image version
###############

prometheus_version: "2.52.0"
alertmanager_version: "0.27.0"
node_exporter_version: "0.18.0"
prometheus_rabbit_exporter_ver: "v0.29.0"
cadvisor_version: "v0.33.0"
prometheus_snmp_exporter_ver: "v0.15.0"
grafana_version: "7.2.2"
haproxy_version: "2.3.1"
keepalived_version: "2.0.17"

####################
# Prometheus options
####################

prometheus_storage_retention: "90d"
prometheus_external_labels:
  monitor: "cloud"
prometheus_scrape_interval: "60s"
prometheus_scrape_timeout: "30s"
prometheus_evaluation_interval: "120s"
