---
# EXAMPLE CONFIGS - MORE IN ansible/group_vars/all.yml

######################
# Service VIP address
######################
ansitheus_vip_address: "10.10.10.1"

ansitheus_network_interface: "eth0"
keepalived_virtual_router_id: "82"

# The group which own node_config_directory, you can use a non-root
config_owner_user: "root"
config_owner_group: "root"

network_interface: "eth0"

###################
# Haproxy Passwords
###################
keepalived_password: "{{ keepalived_password }}"
alertmanager_basic_auth_password: "{{ alertmanager_basic_auth_password }}"
prometheus_basic_auth_password: "{{ prometheus_basic_auth_password }}"

################
# Docker options
################

docker_registry: ""
docker_namespace: ""
docker_registry_username: ""
docker_registry_password: ""

##################
# Service options
##################

enable_prometheus: "yes"
enable_node_exporter: "yes"
enable_cadvisor: "yes"
enable_grafana: "no"
enable_alertmanager: "yes"
enable_haproxy_keepalived: "yes"

##################
# Port mappings
#################

prometheus_port: "9090"
alertmanager_port: "9093"
alertmanager_cluster_port: "9094"
node_exporter_port: "9100"
cadvisor_port: "8080"
grafana_port: "3000"

###############
# Image version
###############

prometheus_version: "2.52.0"
alertmanager_version: "0.27.0"
node_exporter_version: "0.18.0"
prometheus_rabbit_exporter_ver: "v0.29.0"
cadvisor_version: "v0.33.0"
prometheus_snmp_exporter_ver: "v0.15.0"
grafana_version: "7.2.2"
haproxy_version: "2.3.1"
keepalived_version: "2.0.17"

####################
# Prometheus options
####################

prometheus_storage_retention: "90d"
prometheus_external_labels:
  monitor: "cloud"
prometheus_scrape_interval: "60s"
prometheus_scrape_timeout: "30s"
prometheus_evaluation_interval: "120s"

##########################
# Rabbit container options
##########################

rabbit_url: "http://localhost:15672"
rabbit_user: "admin"
rabbit_password: "rabbitpassword"
rabbit_log_level: "debug"
rabbit_output_format: "json"

#################
# Grafana options
#################

grafana_user: "admin"
grafana_password: "password"

###############
# Alert options
###############

alert_via_email: "yes"
alert_mail_account: "fakeaccount@mail"
alert_mail_host: "fakehost"
alert_mail_port: "465"
alert_mail_password: "supersecurepassword"
alert_via_slack: "no"
alert_slack_channel: "fakechannel"
alert_slack_webhook_id: "longwebhookid"

##################
# Grafana options
##################
grafana_data_dir: "/var/lib/grafana"
grafana_logs_dir: "/var/log/grafana"
grafana_plugin_dir: "{{ grafana_data_dir }}/plugins"
# Please check http://docs.grafana.org/installation/configuration/
grafana_database:
  type: sqlite3
  # name: grafana
  # username: admin
  # password: "KbJdz8*U" # Please change me
grafana_remote_cache: {}
grafana_security:
  admin_user: "admin"
  admin_password: "YJ97&Yz$" # Please change me
  #  secret_key: ""
  #  login_remember_days: 7
  #  cookie_username: grafana_user
  #  cookie_remember_name: grafana_remember
  #  disable_gravatar: true
  #  data_source_proxy_whitelist:
grafana_session: {}
#  provider: file
#  provider_config: "sessions"
# grafana authentication mechanisms
grafana_auth: {}
#  disable_login_form: false
#  oauth_auto_login: false
#  disable_signout_menu: false
#  signout_redirect_url: ""
#  anonymous:
#    org_name: "Main Organization"
#    org_role: Viewer
#  ldap:
#    config_file: "/etc/grafana/ldap.toml"
#    allow_sign_up: false
#  basic:
#    enabled: true
grafana_users:
  allow_sign_up: false
  # allow_org_create: true
  # auto_assign_org: true
  auto_assign_org_role: Viewer
  # login_hint: "email or username"
  default_theme: dark
  # external_manage_link_url: ""
  # external_manage_link_name: ""
  # external_manage_info: ""
