---
- name: Restart haproxy_keepalived container
  vars:
    service: "{{ haproxy_keepalived_services['haproxy_keepalived'] }}"
  community.general.docker_container:
    name: "{{ service.container_name }}"
    image: "{{ service.image }}"
    privileged: "{{ service.privileged }}"
    volumes: "{{ service.volumes }}"
    state: "{{ service.state }}"
    network_mode: "{{ service.network_mode }}"
    restart_policy: "{{ service.restart_policy }}"
    log_driver: "{{ service.log_driver }}"
    log_options: "{{ service.log_options }}"
    recreate: "yes"
  when:
    - inventory_hostname in groups[service.group]
    - service.enabled | bool
    - haproxy_copy_config.changed | bool
      or keepalived_copy_config.changed | bool
      or keepalived_copy_check_script.changed | bool
