---
project_name: "haproxy"

haproxy_services:
  haproxy:
    container_name: "haproxy"
    group: "haproxy"
    enabled: "{{ enable_haproxy_keepalived }}"
    image: "{{ haproxy_image_full }}"
    privileged: "no"
    network_mode: "host"
    restart_policy: "unless-stopped"
    state: "started"
    volumes:
      - "{{ haproxy_conf }}:/usr/local/etc/haproxy/:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "haproxy_socket:{{ haproxy_socket_dir }}:rw"
    log_driver: "{{ haproxy_log_driver }}"
    log_options: "{{ haproxy_log_opts }}"
  keepalived:
    container_name: "keepalived"
    group: "haproxy"
    enabled: "{{ enable_keepalived }}"
    image: "{{ keepalived_image_full }}"
    state: "started"
    privileged: "yes"
    network_mode: "host"
    restart_policy: "unless-stopped"
    volumes:
      - "{{ keepalived_conf }}:/usr/local/etc/keepalived/:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "/lib/modules:/lib/modules:ro"
      - "haproxy_socket:{{ haproxy_socket_dir }}:ro"
    log_driver: "{{ keepalived_log_driver }}"
    log_options: "{{ keepalived_log_opts }}"

keepalived_conf: "{{ ansitheus_config_dir }}/keepalived/"
haproxy_conf: "{{ ansitheus_config_dir }}/haproxy/"
haproxy_socket_dir: "/haproxy-sock"

##########
# Docker #
##########

keepalived_image: "{{ docker_registry ~ '/' if docker_registry else '' }}{{ keepalived_docker_namespace }}/keepalived"
keepalived_tag: "{{ keepalived_version }}"
keepalived_image_full: "{{ keepalived_image }}:{{ keepalived_tag }}"

haproxy_image: "{{ docker_registry ~ '/' if docker_registry else '' }}{{ haproxy_docker_namespace ~ '/' if haproxy_docker_namespace else '' }}haproxy"
haproxy_tag: "{{ haproxy_version }}"
haproxy_image_full: "{{ haproxy_image }}:{{ haproxy_tag }}"

haproxy_log_driver: "{{ docker_log_driver }}"
haproxy_log_opts: "{{ docker_log_opts }}"
keepalived_log_driver: "{{ docker_log_driver }}"
keepalived_log_opts: "{{ docker_log_opts }}"

###########
# Configs #
###########

set_sysctl: "yes"
keepalived_traffic_mode: "multicast"

haproxy_max_connections: 6000
haproxy_processes: 1
haproxy_client_timeout: "1m"
haproxy_server_timeout: "1m"

haproxy_defaults_balance: "roundrobin"
