---
haproxy_keepalived_version: "2.8.3-alpine-2.2.8-r0"
haproxy_keepalived_docker_namespace: "{{ docker_namespace if docker_namespace else 'instantlinux' }}"
haproxy_keepalived_image: "{{ docker_registry ~ '/' if docker_registry else '' }}{{ haproxy_keepalived_docker_namespace }}/haproxy-keepalived:{{ haproxy_keepalived_version }}"
haproxy_keepalived_docker_log_driver: "{{ docker_log_driver }}"
haproxy_keepalived_docker_log_opts: "{{ docker_log_opts }}"

keepalived_config_dir: "{{ ansitheus_config_dir }}/keepalived/"
haproxy_config_dir: "{{ ansitheus_config_dir }}/haproxy/"
set_sysctl: "yes"
keepalived_traffic_mode: "multicast"
haproxy_max_connections: 6000
haproxy_client_timeout: "1m"
haproxy_server_timeout: "1m"
haproxy_defaults_balance: "roundrobin"

# Container constructor
# ---------------------
haproxy_keepalived_services:
  haproxy_keepalived:
    container_name: "haproxy_keepalived"
    group: "haproxy_keepalived"
    enabled: "{{ enable_haproxy_keepalived }}"
    image: "{{ haproxy_keepalived_image }}"
    privileged: "yes"
    network_mode: "host"
    restart_policy: "unless-stopped"
    state: "started"
    volumes:
      - "{{ haproxy_config_dir }}:/usr/local/etc/haproxy/:ro"
      - "{{ keepalived_config_dir }}:/etc/keepalived:ro"
      - "/etc/localtime:/etc/localtime:ro"
    log_driver: "{{ haproxy_keepalived_docker_log_driver }}"
    log_options: "{{ haproxy_keepalived_docker_log_opts }}"
    # Uncomment if you want to use vrrp_track_process
    # pid_mode: host
    cap_add:
      - NET_ADMIN
