---
- name: Check free ports for nginx_exporter
  wait_for:
    host: "{{ hostvars[inventory_hostname]['ansible_' + api_interface]['ipv4']['address'] }}"
    port: "{{ item.value.port }}"
    connect_timeout: 1
    timeout: 1
    state: stopped
  when:
    - inventory_hostname in groups[item.value.group]
  with_dict: "{{ nginx_exporter_services }}"
