---
# yamllint disable rule:line-length
argument_specs:
  main:
    short_description: "Prometheus Node Exporter"
    description:
      - "Deploy prometheus L(node exporter,https://github.com/prometheus/node_exporter) using ansible"
    author:
      - "Kien Nguyen Tuan"
    options:
      node_exporter_version:
        description: "Node exporter package version. Also accepts latest as parameter."
        default: "1.8.0"
      node_exporter_web_disable_exporter_metrics:
        description: "Exclude metrics about the exporter itself (promhttp_*, process_*, go_*)."
        type: bool
        default: false
      node_exporter_web_listen_address:
        description: "Address on which node exporter will listen"
        default: "<ip-address>:9100"
      node_exporter_web_telemetry_path:
        description: "Path under which to expose metrics"
        default: "/metrics"
      node_exporter_enabled_collectors:
        description:
          - "List of dicts defining additionally enabled collectors and their configuration."
          - "It adds collectors to L(those enabled by default,https://github.com/prometheus/node_exporter#enabled-by-default)."
        type: "list"
        default:
          - textfile:
              directory: "{{ node_exporter_textfile_dir }}"
      node_exporter_disabled_collectors:
        description:
          - "List of disabled collectors."
          - "By default node_exporter disables collectors listed L(here,https://github.com/prometheus/node_exporter#disabled-by-default)."
        type: "list"
        elements: "str"
      node_exporter_textfile_dir:
        description:
          - "Directory used by the L(Textfile Collector,https://github.com/prometheus/node_exporter#textfile-collector)."
          - "To get permissions to write metrics in this directory, users must be in C(node-exp) system group."
          - "B(Note:) More information in TROUBLESHOOTING.md guide."
        default: "/var/lib/node_exporter"
      node_exporter_tls_server_config:
        description:
          - "Configuration for TLS authentication."
          - "Keys and values are the same as in L(node_exporter docs,https://prometheus.io/docs/prometheus/latest/configuration/https/)."
        type: "dict"
      node_exporter_http_server_config:
        description:
          - "Config for HTTP/2 support."
          - "Keys and values are the same as in L(node_exporter docs,https://prometheus.io/docs/prometheus/latest/configuration/https/)."
        type: "dict"
      node_exporter_basic_auth_users:
        description: "Dictionary of users and password for basic authentication. Passwords are automatically hashed with bcrypt."
        type: "dict"
