---
# yamllint disable rule:line-length
argument_specs:
  main:
    short_description: "Fluentd"
    description:
      - "Deploy Fluentd using ansible"
    author:
      - "Kien Nguyen Tuan"
    options:
      fluentd_version:
        description: "Fluentd version"
        default: "1.17"
      fluentd_env:
        description: "Fluentd environment variables"
        default: "{{ docker_container_env}}"
