---
# yamllint disable rule:line-length
argument_specs:
  main:
    short_description: "Installs and configures prometheus"
    description:
      - "Prometheus monitoring system configuration and management"
    author:
      - "Kien Nguyen Tuan"
    options:
      prometheus_version:
        description:
          - "Prometheus package version. Also accepts C(latest) as parameter."
          - "Only prometheus 2.x is supported"
        default: "2.51.2"
      prometheus_config_dir:
        description: "Path to directory with prometheus configuration"
        default: "/etc/ansitheus/prometheus"
      prometheus_read_only_dirs:
        description: "Additional paths that Prometheus is allowed to read (useful for SSL certs outside of the config directory)"
        type: "list"
        elements: "str"
      prometheus_web_listen_address:
        description: "Address on which prometheus will be listening"
        default: "<ip-address>:9090"
      prometheus_web_config:
        description: "A Prometheus L(web config yaml,https://github.com/prometheus/exporter-toolkit/blob/master/docs/web-configuration.md) for configuring TLS and auth."
        type: "dict"
      prometheus_web_external_url:
        description: "External address on which prometheus is available. Useful when behind reverse proxy. Ex. `http://example.org/prometheus`"
      prometheus_metrics_path:
        description: "Prometheus external metrics path"
        default: "/{{ (prometheus_web_external_url + '/metrics') | regex_replace('^(.*://)?(.*?)/') }}"
      prometheus_storage_retention:
        description:
          - "Data retention period"
        default: "30d"
      prometheus_storage_retention_size:
        description:
          - "Data retention period by size"
          - "Maximum number of bytes that can be stored for blocks."
          - "Units supported: KB, MB, GB, TB, PB."
        default: "0"
      prometheus_agent_mode:
        description:
          - "The Agent mode optimizes Prometheus for the remote write use case. It disables querying, alerting, and local storage, and replaces it with a customized TSDB WAL. L(Everything,https://prometheus.io/docs/prometheus/latest/feature_flags/#prometheus-agent) else stays the same."
          - "This feature is available starting from Prometheus v2.32.0."
        type: bool
        default: false
      prometheus_config_flags_extra:
        description:
          - "Additional configuration flags passed to prometheus binary at startup"
          - "Example: prometheus_config_flags_extra: { storage.tsdb.retention: 15d, alertmanager.timeout: 10s }"
        type: "dict"
      prometheus_global:
        description:
          - "Prometheus global config. It is compatible with the L(official configuration,https://prometheus.io/docs/prometheus/latest/configuration/configuration/#configuration-file)"
        type: "dict"
        default:
          scrape_interval: "60s"
          scrape_timeout: "15s"
          evaluation_interval: "15s"
      prometheus_remote_write:
        description:
          - "Remote write. Compatible with the L(official configuration,https://prometheus.io/docs/prometheus/latest/configuration/configuration/#remote_write)"
        type: "list"
        elements: "str"
      prometheus_remote_read:
        description:
          - "Remote read. It is compatible with the L(official configuration,https://prometheus.io/docs/prometheus/latest/configuration/configuration/#remote_read)"
        type: "list"
        elements: "str"
      prometheus_external_labels:
        description: "Provide map of additional labels which will be added to any time series or alerts when communicating with external systems"
        type: "dict"
        default:
          environment: "{{ ansible_fqdn | default(ansible_host) | default(inventory_hostname) }}"
