---
- name: Ensuring snmp exporter config directories exist
  file:
    path: "{{ ansitheus_conf }}/{{ item.key }}"
    state: "directory"
    owner: "{{ config_owner_user }}"
    group: "{{ config_owner_group }}"
    mode: "0755"
  become: true
  with_dict: "{{ prometheus_exporter_services }}"
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
    - '"prometheus_snmp_exporter" in "{{ item.key }}"'

- name: Find snmp config files for dell server
  local_action:
    module: find
    path: "{{ ansitheus_custom_conf }}/prometheus_exporter/snmp_exporter/"
    pattern: "snmp_exporter_dell_server.yml"
  run_once: True
  register: prometheus_snmp_exporter_dell
  when:
    - enable_prometheus_snmp_exporter_dell_server | bool

- name: Copying over snmp.yml file for dell server
  copy:
    src: "{{ ansitheus_custom_conf }}/prometheus_exporter/snmp_exporter/{{ item.path | basename }}"
    dest: "{{ ansitheus_conf }}/prometheus_snmp_exporter_dell_server/snmp.yml"
    mode: "0755"
  register: prometheus_snmp_exporter_dell_confs
  with_items: "{{ prometheus_snmp_exporter_dell.files }}"
  when:
    - inventory_hostname in groups['prometheus_snmp_exporter_dell_server']
    - enable_prometheus_snmp_exporter_dell_server | bool
    - prometheus_snmp_exporter_dell is defined and prometheus_snmp_exporter_dell.files | length > 0
  notify:
    - Restart prometheus_snmp_exporter_dell_server container

- name: Find snmp config files for hpe device
  local_action:
    module: find
    path: "{{ ansitheus_custom_conf }}/prometheus_exporter/snmp_exporter/"
    pattern: "snmp_exporter_hpe_device.yml"
  run_once: True
  register: prometheus_snmp_exporter_hpe
  when:
    - enable_prometheus_snmp_exporter_hpe_device | bool

- name: Copying over snmp.yml file for hpe device
  copy:
    src: "{{ ansitheus_custom_conf }}/prometheus_exporter/snmp_exporter/{{ item.path | basename }}"
    dest: "{{ ansitheus_conf }}/prometheus_snmp_exporter_hpe_device/snmp.yml"
    mode: "0755"
  register: prometheus_snmp_exporter_hpe_confs
  with_items: "{{ prometheus_snmp_exporter_hpe.files }}"
  when:
    - inventory_hostname in groups['prometheus_snmp_exporter_hpe_device']
    - enable_prometheus_snmp_exporter_hpe_device | bool
    - prometheus_snmp_exporter_hpe is defined and prometheus_snmp_exporter_hpe.files | length > 0
  notify:
    - Restart prometheus_snmp_exporter_hpe_device container

- name: Find snmp config files for fujitsu server
  local_action:
    module: find
    path: "{{ ansitheus_custom_conf }}/prometheus_exporter/snmp_exporter/"
    pattern: "snmp_exporter_fujitsu_server.yml"
  run_once: True
  register: prometheus_snmp_exporter_fujitsu
  when:
    - enable_prometheus_snmp_exporter_fujitsu_server | bool

- name: Copying over snmp.yml file for fujitsu server
  copy:
    src: "{{ ansitheus_custom_conf }}/prometheus_exporter/snmp_exporter/{{ item.path | basename }}"
    dest: "{{ ansitheus_conf }}/prometheus_snmp_exporter_fujitsu_server/snmp.yml"
    mode: "0755"
  register: prometheus_snmp_exporter_fujitsu_confs
  with_items: "{{ prometheus_snmp_exporter_fujitsu.files }}"
  when:
    - inventory_hostname in groups['prometheus_snmp_exporter_fujitsu_server']
    - enable_prometheus_snmp_exporter_fujitsu_server | bool
    - prometheus_snmp_exporter_fujitsu is defined and prometheus_snmp_exporter_fujitsu.files | length > 0
  notify:
    - Restart prometheus_snmp_exporter_fujitsu_server container

- name: Find snmp config files for switch
  local_action:
    module: find
    path: "{{ ansitheus_custom_conf }}/prometheus_exporter/snmp_exporter/"
    pattern: "snmp_exporter_switch.yml"
  run_once: True
  register: prometheus_snmp_exporter_switch
  when:
    - enable_prometheus_snmp_exporter_switch | bool

- name: Copying over snmp.yml file for switch
  copy:
    src: "{{ ansitheus_custom_conf }}/prometheus_exporter/snmp_exporter/{{ item.path | basename }}"
    dest: "{{ ansitheus_conf }}/prometheus_snmp_exporter_switch/snmp.yml"
    mode: "0755"
  register: prometheus_snmp_exporter_switch_confs
  with_items: "{{ prometheus_snmp_exporter_switch.files }}"
  when:
    - inventory_hostname in groups['prometheus_snmp_exporter_switch']
    - enable_prometheus_snmp_exporter_switch | bool
    - prometheus_snmp_exporter_switch is defined and prometheus_snmp_exporter_switch.files | length > 0
  notify:
    - Restart prometheus_snmp_exporter_switch container

- name: Find snmp config files for huawei device
  local_action:
    module: find
    path: "{{ ansitheus_custom_conf }}/prometheus_exporter/snmp_exporter/"
    pattern: "snmp_exporter_huawei_device.yml"
  run_once: True
  register: prometheus_snmp_exporter_huawei_device
  when:
    - enable_prometheus_snmp_exporter_huawei_device | bool

- name: Copying over snmp.yml file for huawei device
  copy:
    src: "{{ ansitheus_custom_conf }}/prometheus_exporter/snmp_exporter/{{ item.path | basename }}"
    dest: "{{ ansitheus_conf }}/prometheus_snmp_exporter_huawei_device/snmp.yml"
    mode: "0755"
  register: prometheus_snmp_exporter_huawei_device_confs
  with_items: "{{ prometheus_snmp_exporter_huawei_device.files }}"
  when:
    - inventory_hostname in groups['prometheus_snmp_exporter_huawei_device']
    - enable_prometheus_snmp_exporter_huawei_device | bool
    - prometheus_snmp_exporter_huawei_device is defined and prometheus_snmp_exporter_huawei_device.files | length > 0
  notify:
    - Restart prometheus_snmp_exporter_huawei_device container

- name: Recreate if not exist running containers
  become: true
  docker_container:
    name: "{{ item.value.container_name }}"
    image: "{{ item.value.image }}"
    volumes: "{{ item.value.volumes }}"
    command: "{{ item.value.command }}"
    state: "{{ item.value.state }}"
    restart_policy: "{{ item.value.restart_policy }}"
    privileged: "{{ item.value.privileged }}"
    network_mode: "{{ item.value.network_mode }}"
    log_driver: "{{ item.value.log_driver }}"
    log_options: "{{ item.value.log_options }}"
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ prometheus_exporter_services }}"
