---
- name: Pull image without running Prometheus exporter containers
  become: true
  docker_image:
    name: "{{ item.value.image }}"
    source: pull
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ prometheus_exporter_services }}"
