---
- name: Ensuring prometheus config directory exist
  file:
    path: "{{ prometheus_config_dir }}"
    state: "directory"
    owner: "{{ config_owner_user }}"
    group: "{{ config_owner_group }}"
    mode: 0755

- name: Find custom prometheus alert rule files
  local_action:
    module: find
    path: "{{ ansitheus_custom_config_dir }}/prometheus/rules/"
    pattern: "*.yml,*.yaml"
  run_once: true
  register: prometheus_alert_rules

- name: Ensuring rules directory exist
  file:
    path: "{{ ansitheus_custom_config_dir }}/prometheus/rules/"
    state: "directory"
    mode: 0755
  when:
    - prometheus_alert_rules is defined and prometheus_alert_rules.files | length > 0

- name: Copying over custom prometheus alert rules files
  copy:
    src: "{{ ansitheus_custom_config_dir }}/prometheus/rules"
    dest: "{{ prometheus_config_dir }}"
    mode: 0755
  register: prometheus_alert_confs
  when:
    - prometheus_alert_rules.stat.isdir is defined and prometheus_alert_rules.stat.isdir
  notify:
    - Reload prometheus config

- name: Check custom file_sd files exists
  local_action:
    module: find
    path: "{{ ansitheus_custom_config_dir }}/prometheus/file_sd"
    pattern: "*.json"
  run_once: true
  register: prometheus_file_sd

- name: Copying over custom file_sd
  copy:
    src: "{{ ansitheus_custom_config_dir }}/prometheus/file_sd"
    dest: "{{ prometheus_config_dir }}"
    mode: 0755
  register: prometheus_file_sd_confs
  when:
    - prometheus_file_sd.stat.isdir is defined and prometheus_file_sd.stat.isdir
  notify:
    - Reload prometheus config

- name: Configure Prometheus web
  ansible.builtin.copy:
    content: "{{ prometheus_web_config | to_nice_yaml(indent=2, sort_keys=False) }}"
    dest: "{{ prometheus_config_dir }}/web.yml"
    force: true
    mode: 0755

- name: Copying over prometheus config file
  template:
    src: "{{ item }}"
    dest: "{{ prometheus_config_dir }}/prometheus.yml"
    mode: 0755
  register: prometheus_confs
  with_first_found:
    - "{{ ansitheus_custom_config_dir }}/prometheus/{{ inventory_hostname }}/prometheus.yml"
    - "{{ ansitheus_custom_config_dir }}/prometheus/prometheus.yml"
    - "{{ role_path }}/templates/prometheus.yml.j2"
  notify:
    - Reload prometheus config

- name: Check prometheus containers
  docker_container:
    name: "{{ item.value.container_name }}"
    image: "{{ item.value.image }}"
    volumes: "{{ item.value.volumes }}"
    command: "{{ item.value.command }}"
    state: "{{ item.value.state }}"
    restart_policy: "{{ item.value.restart_policy }}"
    privileged: "{{ item.value.privileged }}"
    network_mode: "{{ item.value.network_mode }}"
    log_driver: "{{ item.value.log_driver }}"
    log_options: "{{ item.value.log_options }}"
  with_dict: "{{ prometheus_services }}"
