---
- name: Check free port for Prometheus server
  wait_for:
    host: "{{ hostvars[inventory_hostname]['ansible_' + api_interface]['ipv4']['address'] }}"
    port: "{{ prometheus_port }}"
    connect_timeout: 1
    timeout: 1
    state: stopped
  when:
    - inventory_hostname in groups[item.value.group]
  with_dict: "{{ prometheus_services }}"
