---
- import_playbook: gather-facts.yml
  when: not skip_gather_fact | bool

- name: Apply role common
  gather_facts: false
  hosts:
    - common
  roles:
    - { role: common, tags: common, when: enable_common | bool }

- name: Apply role haproxy
  gather_facts: false
  become: true
  hosts:
    - haproxy
  roles:
    - { role: haproxy, tags: haproxy, when: enable_haproxy | bool }

- name: Apply role prometheus
  gather_facts: false
  become: true
  hosts:
    - prometheus
  roles:
    - { role: prometheus, tags: prometheus, when: enable_prometheus | bool }

- name: Apply role alertmanager
  gather_facts: false
  become: true
  hosts:
    - alertmanager
  roles:
    - {
        role: alertmanager,
        tags: alertmanager,
        when: enable_alertmanager | bool,
      }

- name: Apply role node_exporter
  gather_facts: false
  become: true
  hosts:
    - node_exporter
  roles:
    - {
        role: node_exporter,
        tags: [exporters, node_exporter],
        when: enable_node_exporter | bool,
      }

- name: Apply role node_exporter
  gather_facts: false
  become: true
  hosts:
    - cadvisor
  roles:
    - {
        role: cadvisor,
        tags: [exporters, cadvisor],
        when: enable_cadvisor | bool,
      }

- name: Apply role grafana
  gather_facts: false
  become: true
  hosts:
    - grafana
  roles:
    - { role: grafana, tags: grafana, when: enable_grafana | bool }
