---
- name: Recreate grafana container
  vars:
    service: "{{ grafana_services['grafana'] }}"
  community.general.docker_container:
    name: "{{ service.container_name }}"
    image: "{{ service.image }}"
    privileged: "{{ service.privileged }}"
    volumes: "{{ service.volumes }}"
    state: "{{ service.state }}"
    network_mode: "{{ service.network_mode }}"
    restart_policy: "{{ service.restart_policy }}"
    recreate: "yes"
  when:
    - inventory_hostname in groups[service.group]
    - service.enabled | bool
    - grafana_confs.changed | bool
      or grafana_plugins.changed | bool
      or grafana_extra_confs.changed | bool
