---
- name: Restart fluentd container
  vars:
    service: "{{ fluentd_services['fluentd'] }}"
  docker_container:
    name: "{{ service.container_name }}"
    image: "{{ service.image }}"
    privileged: "{{ service.privileged }}"
    volumes: "{{ service.volumes }}"
    state: "{{ service.state }}"
    network_mode: "{{ service.network_mode }}"
    restart_policy: "{{ service.restart_policy }}"
    recreate: "yes"
  when:
    - inventory_hostname in groups[service.group]
    - service.enabled | bool
    - fluentd_input.changed | bool
      or fluentd_input_custom.changed | bool
      or fluentd_filter.changed | bool
      or fluentd_filter_custom.changed | bool
      or fluentd_format.changed | bool
      or fluentd_format_custom.changed | bool
      or fluentd_output.changed | bool
      or fluentd_output_custom.changed | bool
      or fluentd_td_agent | bool
