---
- name: Ensuring config directory exist
  file:
    path: "{{ prometheus_alertmanager_conf }}"
    state: "directory"
    owner: "{{ config_owner_user }}"
    group: "{{ config_owner_group }}"
    mode: "0755"
  become: true
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ prometheus_alertmanager_services }}"

- name: Find custom prometheus alertmanager custom template files
  local_action:
    module: find
    path: "{{ ansitheus_custom_conf }}/prometheus_alertmanager/template"
    pattern: "*.tmpl"
  run_once: true
  become: true
  register: prometheus_alertmanager_custom_template_files

- name: Check if custom alertmanager config exists
  local_action: "stat path={{ ansitheus_custom_conf }}/prometheus_alertmanager/config.yml"
  register: prometheus_alertmanager_config_file
  run_once: True

- name: Ensuring custom template directory exist
  file:
    path: "{{ prometheus_alertmanager_conf }}/template/"
    state: "directory"
    mode: "0755"
  become: true
  when:
    - prometheus_alertmanager_custom_template_files is defined and prometheus_alertmanager_custom_template_files.files | length > 0

- name: Copying custom prometheus alertmanager custom template files if exists
  copy:
    src: "{{ item.path }}"
    dest: "{{ prometheus_alertmanager_conf }}/template/{{ item.path | basename }}"
    mode: "0755"
  register: prometheus_alertmanager_custom_templates
  become: true
  when:
    - prometheus_alertmanager_custom_template_files is defined and prometheus_alertmanager_custom_template_files.files | length > 0
  with_items: "{{ prometheus_alertmanager_custom_template_files.files }}"
  notify:
    - Reload prometheus_alertmanager config

- name: Copying over custom prometheus alertmanager config file if exists
  vars:
    service: "{{ prometheus_alertmanager_services['prometheus_alertmanager']}}"
  copy:
    src: "{{ ansitheus_custom_conf }}/prometheus_alertmanager/config.yml"
    dest: "{{ prometheus_alertmanager_conf }}/config.yml"
  register: prometheus_alertmanager_custom_confs
  when:
    - inventory_hostname in groups[service.group]
    - service.enabled | bool
    - prometheus_alertmanager_config_file.stat.exists
  notify:
    - Reload prometheus_alertmanager config

- name: Copying over prometheus alertmanager config file
  vars:
    service: "{{ prometheus_alertmanager_services['prometheus_alertmanager']}}"
  template:
    src: "prometheus_alertmanager.yml.j2"
    dest: "{{ prometheus_alertmanager_conf }}/config.yml"
    mode: "0755"
  register: prometheus_alertmanager_confs
  become: true
  when:
    - inventory_hostname in groups[service.group]
    - service.enabled | bool
    - not prometheus_alertmanager_config_file.stat.exists
  notify:
    - Reload prometheus_alertmanager config

- name: Check prometheus_alertmanager containers
  become: true
  docker_container:
    name: "{{ item.value.container_name }}"
    image: "{{ item.value.image }}"
    volumes: "{{ item.value.volumes }}"
    command: "{{ item.value.command }}"
    state: "{{ item.value.state }}"
    restart_policy: "{{ item.value.restart_policy }}"
    privileged: "{{ item.value.privileged }}"
    network_mode: "{{ item.value.network_mode }}"
    log_driver: "{{ item.value.log_driver }}"
    log_options: "{{ item.value.log_options }}"
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ prometheus_alertmanager_services }}"
