---
- name: Pull image without running Prometheus alertmanager container
  docker_image:
    name: "{{ item.value.image }}"
    source: pull
  become: true
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ prometheus_alertmanager_services }}"
