---
# yamllint disable rule:line-length
argument_specs:
  main:
    short_description: "Prometheus nginx_exporter"
    description:
      - "Deploy prometheus L(nginx exporter,https://github.com/nginxinc/nginx-prometheus-exporter) using ansible"
    author:
      - "Prometheus Community"
    options:
      nginx_exporter_version:
        description: "nginx_exporter package version. Also accepts latest as parameter."
        default: "1.4.1"
      nginx_exporter_plus:
        description: "Start the exporter for NGINX Plus."
        type: bool
        default: false
      nginx_exporter_web_listen_address:
        description: "Address on which nginx exporter will listen"
        default: "0.0.0.0:9113"
      nginx_exporter_web_telemetry_path:
        description: "Path under which to expose metrics"
        default: "/metrics"
      nginx_exporter_tls_server_config:
        description:
          - "Configuration for TLS authentication."
          - "Keys and values are the same as in L(nginx_exporter docs,https://github.com/prometheus/exporter-toolkit/blob/master/docs/web-configuration.md)."
        type: "dict"
      nginx_exporter_http_server_config:
        description:
          - "Config for HTTP/2 support."
          - "Keys and values are the same as in L(nginx_exporter docs,https://github.com/prometheus/exporter-toolkit/blob/master/docs/web-configuration.md)."
        type: "dict"
      nginx_exporter_basic_auth_users:
        description: "Dictionary of users and password for basic authentication. Passwords are automatically hashed with bcrypt."
        type: "dict"
      nginx_exporter_scrape_uri:
        description: "A URI or unix domain socket path for scraping NGINX or NGINX Plus metrics. For NGINX, the stub_status page must be available through the URI."
        default: "http://127.0.0.1/stub_status"
      nginx_exporter_config_dir:
        description: "Path to directory with nginx_exporter configuration"
        default: "/etc/nginx_exporter"
